apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts-jdk11
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 50000

            
        volumeMounts:
          - name: jenkins-vol2
            mountPath: /var/jenkins_vol2

          - name: docker
            mountPath: /var/run/docker.sock

          - name: docker
            mountPath: /usr/bin/docker
            subPath: docker

          - name: kubectlah
            mountPath: /usr/bin/kubectl
            subPath: kubectl

          

      initContainers:
      - name: dockercli
        image: docker
        command: ["cp","/usr/local/bin/docker", "/opt/temp"]
 

        volumeMounts:
          - name: docker
            mountPath: /opt/temp

      - name: kubectlah
        image: alpine/k8s:1.23.13
        command: ["cp","/usr/bin/kubectl", "/opt/newtemp"]
 

        volumeMounts:
          - name: docker
            mountPath: /opt/temp

          - name: kubectlah
            mountPath: /opt/newtemp


      volumes:
      - name: docker
        emptyDir: {}

      - name: dockersock
        hostPath:
          path: /var/run/docker.sock


      - name: kubectlah
        emptyDir: {}

      - name: jenkins-vol2
        emptyDir: {}
          
        
          
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: jenkins

---

apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins